name: tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install bats
        run: sudo apt-get install -y bats

      - name: run tests
        run: sudo bats test/mkusers.bats
